import { Fragment } from "react";




export const metadata = {
    title: 'Create asdasd App',
    description: 'Generated by create next app',
}

const ProductDetail = async ({ params }: { params: any }) => {
    const res = await fetch("http://localhost:3000/api/users").then((r) => r.json());
    var data = res;
    console.log(params);
    metadata.description = "Abc";
    metadata.title = "asdasd";

    return (
        <>
            {
                data.map((res: any) => (
                    <Fragment>
                        <div>{res.Username} </div>
                    </Fragment>
                ))
            }
            <div>Test</div>
        </>

    )
}

// export async function getServerSideProps(context: any) {
//     const { name } = context.query;
//     const res = await fetch("http://localhost:3000/api/users");
//     const data = 'asdasd';
//     // Pass data to the page via props
//     return { props: { data } };
// }

export default ProductDetail;